export const LogPrefix = {
  success: '[✅]',
  error: '[❌]',
  stop: '[⛔️]',
  search: '[🔍]',
  debug: '[🐞]',
  ignore: '[💀]',
  warning: '[⚠️]',
  info: '[ℹ️]',
  start: '[🚀]',
  finish: '[✅]',
  wait: '[⏳]',
  retry: '[🔁]',
  pause: '[⏸️]',
  resume: '[▶️]',
  time: '[⏰]',
  graduated: '[🎓]',
  launched: '[🚀]',
  swap: '[🔄]',
}